DELIMITER $$
CREATE PROCEDURE listarFaltasTurma()
BEGIN
DECLARE RA_ALUNO VARCHAR(50);
DECLARE NOME_ALUNO VARCHAR(70);
DECLARE DATA_1 DATE;
DECLARE DATA_2 DATE;
DECLARE TOTAL_FALTAS INT;
DECLARE TOTAL_PRESENCAS INT;
DECLARE TERMINOU INT DEFAULT 0;

DECLARE CONSULTA_ALUNO CURSOR FOR SELECT RA FROM ALUNO;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET TERMINOU = 1;
OPEN CONSULTA_ALUNO;

	CONSULTA_ALUNOS : LOOP
		FETCH CONSULTA_ALUNO INTO RA_ALUNO;
        IF TERMINOU = 1 THEN
			LEAVE CONSULTA_ALUNOS;
		END IF;

        SET NOME_ALUNO = (SELECT A.NOME FROM ALUNO A WHERE A.RA = RA_ALUNO);
        SET TOTAL_FALTAS = (SELECT COUNT(*) FROM FALTAS F WHERE F.RA_ALUNO = RA_ALUNO AND F.PRESENCA = 'F');
        SET TOTAL_PRESENCAS = (SELECT COUNT(*) FROM FALTAS F WHERE F.RA_ALUNO = RA_ALUNO AND F.PRESENCA ='P');
		SET DATA_1 = (SELECT DATA_AULA FROM FALTAS F WHERE F.RA_ALUNO = RA_ALUNO);

        INSERT INTO RELACAO_FALTAS_TURMA VALUES(RA_ALUNO, NOME_ALUNO, DATA_1, DATA_1, TOTAL_FALTAS,TOTAL_PRESENCAS);
	END LOOP;

		SELECT * FROM RELACAO_FALTAS_TURMA;
END
$$