DELIMITER $$
CREATE PROCEDURE listarSituacaoTurma()

BEGIN
DECLARE RA_ALUNO VARCHAR(50);
DECLARE NOME_ALUNO VARCHAR(70);
DECLARE NOTA_1 DECIMAL(10, 0);
DECLARE NOTA_2 DECIMAL(10, 0);
DECLARE SITUACAO_ALUNO CHAR(1);
DECLARE MEDIA_FINAL DECIMAL(10, 0);
DECLARE FIM INT DEFAULT 0;
DECLARE TERMINOU INT DEFAULT 0;

DECLARE CONSULTA_RA CURSOR FOR SELECT A.RA FROM ALUNO AS A;
DECLARE CONTINUE HANDLER FOR NOT FOUND SET TERMINOU = 1;

OPEN CONSULTA_RA;
   CONSULTA_ALUNOS : LOOP
	FETCH CONSULTA_RA INTO RA_ALUNO;
		IF TERMINOU = 1 THEN
			LEAVE CONSULTA_ALUNOS;
		END IF;

        SET NOME_ALUNO = (SELECT A.NOME FROM ALUNO AS A WHERE A.RA = RA_ALUNO);
        SET NOTA_1 = (SELECT N.NOTA FROM NOTA N WHERE N.RA_ALUNO = RA_ALUNO);
        SET NOTA_2 = (SELECT N.NOTA_2 FROM NOTA N WHERE N.RA_ALUNO = RA_ALUNO);

		SET MEDIA_FINAL = (NOTA_1 + NOTA_2) / 2;

	  IF MEDIA_FINAL < 6.0 THEN
			SET SITUACAO_ALUNO = 'R';
	 	ELSE IF MEDIA_FINAL >= 6.0 THEN
			SET SITUACAO_ALUNO = 'A';
		END IF;
	  END IF;

		INSERT INTO RELACAO_ALUNOS_TURMA VALUES (RA_ALUNO, NOME_ALUNO, NOTA_1, MEDIA_FINAL, SITUACAO_ALUNO, NOTA_2);
   END LOOP CONSULTA_ALUNOS;

   SELECT * FROM RELACAO_ALUNOS_TURMA;
END
$$
