CREATE TABLE ALUNO(
RA VARCHAR(50) NOT NULL,
NOME VARCHAR(200),
PRIMARY KEY(RA)
);

CREATE TABLE DISCIPLINA(
CODIGO VARCHAR(50),
NOME VARCHAR(50),
SIGLA VARCHAR(10),
TURNO CHAR(1),
QUANTIDADE_AULAS INT,
PRIMARY KEY (CODIGO)
);

CREATE TABLE AVALIACAO(
CODIGO INT NOT NULL,
TIPO VARCHAR(30),
PRIMARY KEY (CODIGO)
);

CREATE TABLE NOTA(
RA_ALUNO VARCHAR(50) NOT NULL,
CODIGO_DISCIPLINA VARCHAR (50),
CODIGO_AVALIACAO INT NOT NULL,
NOTA DECIMAL,
FOREIGN KEY (RA_ALUNO) REFERENCES ALUNO (RA),
FOREIGN KEY (CODIGO_DISCIPLINA) REFERENCES DISCIPLINA (CODIGO),
FOREIGN KEY (CODIGO_AVALIACAO) REFERENCES AVALIACAO (CODIGO)
);

CREATE TABLE FALTAS (
RA_ALUNO VARCHAR (50) NOT NULL,
CODIGO_DISCIPLINA VARCHAR (50),
DATA_AULA DATE,
PRESENCA CHAR(1),
PRIMARY KEY (DATA_AULA),
FOREIGN KEY (RA_ALUNO) REFERENCES ALUNO (RA),
FOREIGN KEY (CODIGO_DISCIPLINA) REFERENCES DISCIPLINA (CODIGO)
);